# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Spyen_config = debug
  Spoiled_config = debug

else ifeq ($(config),release)
  Spyen_config = release
  Spoiled_config = release

else ifeq ($(config),dist)
  Spyen_config = dist
  Spoiled_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Spyen Spoiled

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Spyen:
ifneq (,$(Spyen_config))
	@echo "==== Building Spyen ($(Spyen_config)) ===="
	@${MAKE} --no-print-directory -C Spyen -f Makefile config=$(Spyen_config)
endif

Spoiled:
ifneq (,$(Spoiled_config))
	@echo "==== Building Spoiled ($(Spoiled_config)) ===="
	@${MAKE} --no-print-directory -C Spoiled -f Makefile config=$(Spoiled_config)
endif

clean:
	@${MAKE} --no-print-directory -C Spyen -f Makefile clean
	@${MAKE} --no-print-directory -C Spoiled -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Spyen"
	@echo "   Spoiled"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"