#pragma once

#include "spypch.h"

namespace Spyen
{
	using KeyCode = uint16_t;

	enum : KeyCode {
        SPKC_A = 4,
        SPKC_B = 5,
        SPKC_C = 6,
        SPKC_D = 7,
        SPKC_E = 8,
        SPKC_F = 9,
        SPKC_G = 10,
        SPKC_H = 11,
        SPKC_I = 12,
        SPKC_J = 13,
        SPKC_K = 14,
        SPKC_L = 15,
        SPKC_M = 16,
        SPKC_N = 17,
        SPKC_O = 18,
        SPKC_P = 19,
        SPKC_Q = 20,
        SPKC_R = 21,
        SPKC_S = 22,
        SPKC_T = 23,
        SPKC_U = 24,
        SPKC_V = 25,
        SPKC_W = 26,
        SPKC_X = 27,
        SPKC_Y = 28,
        SPKC_Z = 29,

        SPKC_1 = 30,
        SPKC_2 = 31,
        SPKC_3 = 32,
        SPKC_4 = 33,
        SPKC_5 = 34,
        SPKC_6 = 35,
        SPKC_7 = 36,
        SPKC_8 = 37,
        SPKC_9 = 38,
        SPKC_0 = 39,

        SPKC_RETURN = 40,
        SPKC_ESCAPE = 41,
        SPKC_BACKSPACE = 42,
        SPKC_TAB = 43,
        SPKC_SPACE = 44,

        SPKC_MINUS = 45,
        SPKC_EQUALS = 46,
        SPKC_LEFTBRACKET = 47,
        SPKC_RIGHTBRACKET = 48,
        SPKC_BACKSLASH = 49, 
        SPKC_NONUSHASH = 50,
        SPKC_SEMICOLON = 51,
        SPKC_APOSTROPHE = 52,
        SPKC_GRAVE = 53,
        SPKC_COMMA = 54,
        SPKC_PERIOD = 55,
        SPKC_SLASH = 56,

        SPKC_CAPSLOCK = 57,

        SPKC_F1 = 58,
        SPKC_F2 = 59,
        SPKC_F3 = 60,
        SPKC_F4 = 61,
        SPKC_F5 = 62,
        SPKC_F6 = 63,
        SPKC_F7 = 64,
        SPKC_F8 = 65,
        SPKC_F9 = 66,
        SPKC_F10 = 67,
        SPKC_F11 = 68,
        SPKC_F12 = 69,

        SPKC_PRINTSCREEN = 70,
        SPKC_SCROLLLOCK = 71,
        SPKC_PAUSE = 72,
        SPKC_INSERT = 73,
        SPKC_HOME = 74,
        SPKC_PAGEUP = 75,
        SPKC_DELETE = 76,
        SPKC_END = 77,
        SPKC_PAGEDOWN = 78,
        SPKC_RIGHT = 79,
        SPKC_LEFT = 80,
        SPKC_DOWN = 81,
        SPKC_UP = 82,

        SPKC_NUMLOCKCLEAR = 83, 
        SPKC_KP_DIVIDE = 84,
        SPKC_KP_MULTIPLY = 85,
        SPKC_KP_MINUS = 86,
        SPKC_KP_PLUS = 87,
        SPKC_KP_ENTER = 88,
        SPKC_KP_1 = 89,
        SPKC_KP_2 = 90,
        SPKC_KP_3 = 91,
        SPKC_KP_4 = 92,
        SPKC_KP_5 = 93,
        SPKC_KP_6 = 94,
        SPKC_KP_7 = 95,
        SPKC_KP_8 = 96,
        SPKC_KP_9 = 97,
        SPKC_KP_0 = 98,
        SPKC_KP_PERIOD = 99,
	};
}